Migrate to vite
SDFIdk/Koordinattransformation pull request #69
Opened 2023-02-15 12:07 UTC by PelleSwelle

Vue CLI er nu udskiftet til [Vite](https://vitejs.dev/).
Dette er gjort fordi: 

- for at følge med industry standard, 
- for at kunne implementere testing med Vitest
- for ikke at skulle skrive `--legacy-peer-deps` efter hver npm install
- for en MEGET hurtigere hot reload.

For at smide den på localhost, skal man ikke længere skrive `npm run serve`, men derimod `npm run dev`
Denne opdatering gør det også nødvendigt at ændre lidt i .env filerne:

forekomster af prefixet `VUE_APP` skal ændres til `VITE`. Eksempel `VUE_APP_NODE_ENV` => `VITE_NODE_ENV`
Dette skal nok også opdateres i [Koordinattransformation-config](https://github.com/SDFIdk/Koordinattransformation-config)

2023-02-15 12:25 UTC, kbevers commented
Ved første øjekast ser det godt ud. Jeg giver det et grundigere kig lidt senere når jeg har bedre tid og vender tilbage.

> Dette skal nok også opdateres i [Koordinattransformation-config](https://github.com/SDFIdk/Koordinattransformation-config)

Vil du ikke lave et PR på det? Til en start bare på test-opsætningen.

2023-02-15 14:13 UTC, PelleSwelle commented
Der er en PR i Koordinattransformation-config nu

2023-02-17 11:04 UTC, kbevers requested changes
Jeg har forsøgt mig med at bygge og køre siden lokalt på min egen maskine. Det lykkes ikke helt. Jeg tror primært det skyldes at jeg (som aldrig har lavet en webside med javascript, npm og andet smart teknik) ikke får tilstrækkeligt hjælp i README'en.

Så den har jeg til en start nogle kommentarer til:

1. Jeg savner en beskrivelse af hvordan npm smartest installeres på en Windows PC. Der er tilsyneladende flere muligheder, jeg vil gerne have hjælp til at vælge den rigtige. For nuværende har jeg installeret det på min private computer (fordi der er bøvl med VPN'en...). Det her jeg gjort med `brew install npm` hvilket lader til at fungere fint.
2. Sektionen om "environment variables" er forvirrende. Det er terminologien den er galt med. Måske er det almindeligt npm/javascript/whatever-sprog, men det skabaer begrebsforvirring hos mig da en [environment variable](https://en.wikipedia.org/wiki/Environment_variable) (miljøvariabel på dansk) normalt ikke er noget der bor i en fil. Det er dog klart her at det er noget der skal stå i en fil men navnet på filen er ikke angivet. Jeg kan sjusse mig frem til, via koordinattransformation-config, at det nok er en fil der hedder `.env.development`. Det bør stå i README-filen. Ligeledes hvis det også er muligt at have en `.env.production` eller lignende.
3. Jeg får en fejl når jeg kører `npm run build`:
```
$ npm run build                                                                               
> koordinattransformation-vue@0.1.0 build
> vite build

vite v2.9.15 building for production...
✓ 10 modules transformed.
[vite:load-fallback] Could not load /Users/kevers/dev/Koordinattransformation/src/components/shared/Icon (imported by src/main.js): ENOENT: no such file or directory, open '/Users/kevers/dev/Koordinattransformation/src/components/shared/Icon'
error during build:
Error: Could not load /Users/kevers/dev/Koordinattransformation/src/components/shared/Icon (imported by src/main.js): ENOENT: no such file or directory, open '/Users/kevers/dev/Koordinattransformation/src/components/shared/Icon'
```
Det er der måske en god forklaring på, men det er ikke klart for mig om jeg har gjort noget forkert i opsætningen eller om det er en fejl i koden.
4. Der er henvisninger til Vue.js et par steder, er det ikke irrelevant med den her opdatering?
5. Når jeg kører `npm run dev` kan jeg godt tilgå websiden lokalt. Den indlæser kortbaggrunden men jeg har ikke nogle koordinatsystemer at vælge mellem i de to dropdownmenuer. Jeg gætter på det er en konfigurationsfejl fra min side, men igen, som ikke-indviet javascriptperson er det ikke åbenlyst hvad jeg skal gøre.

2023-02-20 09:15 UTC, PelleSwelle commented
1. Helt enig med hensyn til readme'en. Den bliver opdateret hurtigst muligt. 
2. Der skal også komme en udførlig beskrivelse af det med miljøvariabler i readme'en. Der skal jeg lige forhøre mig med en af de andre, da der er noget sikkerhedsmæssigt med hensyn til det.
3. npm build bygger til produktion og forsøger derfor at skære det fra, som ikke bliver brugt, og ikonerne bliver ikke brugt længere. (bliver nu varetaget af en npm package) Har bare ikke slettet dem endnu for en sikkerheds skyld.
4. vue.js er stadig aktuelt. Det er build toolet vue_cli, som er skiftet til Vite.
5. manglende koordinatsystemer hører sammen med miljøvariable, så det bliver løst, når der kommer en opdatering af readme'en.

2023-02-20 12:57 UTC, PelleSwelle commented
Jeg har lige pushet til migrate-to-vite branchen, og det burde vist nok være nok til, at den bliver opdateret herinde. 
Kan du se det nu?

2023-02-20 18:53 UTC, kbevers commented
> Kan du se det nu?

Yes. Tak, det er meget bedre nu!

Jeg har stadig ikke held til at få siden til at virke rigtigt lokalt. Baggrundskortet kommer frem men jeg kan ikke vælge nogle koordinatsystemer i dropdown-menuerne:

<img width="1506" alt="Screen Shot 2023-02-20 at 19 47 28" src="https://user-images.githubusercontent.com/13132571/220180722-a4f521ad-1b35-4fdf-852f-298a224e1744.png">

Jeg går ud fra at tokens osv fungerer da baggrundskortet vises. Jeg har kopieret filerne fra dit PR i kooordinattransformation-config. Jeg har desuden prøvet lidt forskellige kombinationer af adressen i `VITE_API_BASE_URL` for at elimenere evt fejl der men uden held.

Det er med stor sandsynlighed en fejl hos mig, jeg kan bare ikke regne ud hvad det er. 

Til forskel fra før kan jeg nu kører `npm run build` uden fejl. Jeg får følgende ved linting:

```
$ npm run lint                                                                                [19:44:45]

> koordinattransformation-vue@0.1.0 lint
> eslint --ext .js,.vue --ignore-path .gitignore --fix src


Oops! Something went wrong! :(

ESLint: 8.34.0

/Users/kevers/dev/Koordinattransformation/.eslintrc.js:11
    'no-console': import.meta.env.NODE_ENV !== 'production' ? 'off' : 'error',
                         ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1195:20)
    at Module._compile (node:internal/modules/cjs/loader:1239:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at module.exports [as default] (/Users/kevers/dev/Koordinattransformation/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/kevers/dev/Koordinattransformation/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2562:47)
    at loadConfigFile (/Users/kevers/dev/Koordinattransformation/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2646:20)
```

Om det er et reelt problem kan jeg ikke vurdere. Jeg tror heller ikke jeg selv kan finde løsning på mit problem med siden men hvis du er ellers føler dig sikker på at det virker så lad os bare merge og deploye den på test-serveren.

2023-02-20 18:54 UTC, kbevers approved these changes

2023-02-21 18:08 UTC, PelleSwelle commented
Jeg vil lige få tjekket om alt det med tokens og sådan noget er som det skal være, før vi smider det op.
Siger konsollen noget til dig?

2023-02-22 07:47 UTC, kbevers commented
Her er alt jeg får: 

```
$ npm run dev                                                                                  

> koordinattransformation-vue@0.1.0 dev
> vite

Port 3000 is in use, trying another one...

  vite v2.9.15 dev server running at:

  > Local: http://localhost:3001/
  > Network: use `--host` to expose

  ready in 123ms.

[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

[@vue/compiler-sfc] `defineEmits` is a compiler macro and no longer needs to be imported.
```

Umiddelbart ikke så hjælpsomt.

2023-02-22 08:15 UTC, PelleSwelle commented
Nej, jeg mener devtools i browseren

2023-02-22 08:59 UTC, kbevers commented
> Nej, jeg mener devtools i browseren

Det aner jeg ikke noget om. Husk at jeg ikke ved noget som helst om javascript, webbrowsere og alt der i mellem ;-) Jeg kan godt kigge efter men så har jeg brug for en udførlig vejledning i hvordan.

2023-02-22 11:29 UTC, PelleSwelle commented
Helt sikkert. Vi kan lige kigge på det i morgen, når jeg kommer på kontoret.

2023-02-23 08:56 UTC, merged