Sdfi design system
SDFIdk/Koordinattransformation pull request #78
Opened 2023-06-01 12:04 UTC by PelleSwelle

indledende implementering af SDFI design system.
og generel oprydning af en masse dobbeltkonfekt rundt omkring.
i sammenhæng med implementering er en del komponenter også reformateret og skrevet om til den mere moderne og langt mindre verbose [script setup syntax](https://vuejs.org/api/sfc-script-setup.html).

2023-06-01 13:21 UTC, kbevers requested changes
Et par småting, der primært omhandler udkommenteret kode som vist lige så godt bare kan slettes

2023-06-01 13:21 UTC, kbevers commented on src/assets/css/base.css
> +/* :root, html {
Det ligner at du udkommenterer en større blok her (linje 1-111) - skal det ikke bare fjernes i stedet?

2023-06-01 13:21 UTC, kbevers commented on src/assets/css/fonts.css
>      font-family: 'Roboto';
Det ligner at du udkommenterer en større blok her (linje 1-192) - skal det ikke bare fjernes i stedet?

2023-06-01 13:21 UTC, kbevers commented on src/assets/css/grid.css
> +}
Du kan undgå de her "stopskilte" ved at slutte filen med en tom linje (det er en mærkelig ting med Windows).

2023-06-01 13:21 UTC, kbevers commented on src/components/coordinatetransformation/CoordinateTransformation.vue
> +//   }
Slet udkommenteret kode
```suggestion
```

2023-06-19 07:54 UTC, PelleSwelle commented on src/assets/css/fonts.css
>      font-family: 'Roboto';
hele filen er slettet nu

2023-06-19 07:54 UTC, PelleSwelle commented on src/assets/css/base.css
> +/* :root, html {
hele filen slettet nu

2023-06-19 09:14 UTC, kbevers approved these changes
Det ser godt ud!

2023-06-19 09:26 UTC, merged